apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: sumapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sumapp
    spec:
      containers:
      - name: liberty4all
        image: mycluster.icp:8500/demo/sumapp
        ports:
        - containerPort: 9080
